### ISSUE TITLE
PointsOfInterest layer not displayed without a 'Location' address

### ISSUE THREAD

**Issue by lhasselb** [gordonbanderson/MappablePointsOfInterest#5]
I am using the configuration option to extend an existing page type like

``` yml
PageWithPointsOfInterest:
  extensions:
    ['MapExtension', 'PointsOfInterestLayerExtension']
```

It seems the POI-Layer is not displayed without adding a address into the Location tab.
After adding an address to the "Location" tab the POI-Layer is displayed without a problem.
But after adding the address to the Location tab it is displayed as an additional marker on the map.
Did I miss something?

Antother minor thing:
In a setup mentioned above the POIs are clustered by default. 
Would it be possible to add a configuration parameter
similar to the already existing method `$map->setClusterer( true );` to disable clustering
with something like below ?
`PointsOfInterestLayerExtension:`
`cluster: false`
